export default {
  title: "Bright Raven",
  url: "https://blog.brightraven.world",
  feedUrl: {
    en: "/feed.xml",
    ja: "/ja/feed.xml",
    "zh-TW": "/zh/feed.xml",
  },
  author: {
    name: "Bertram (Bright Raven)",
    email: "bertram@brightraven.world",
  },
  studio: {
    name: "Bright Raven",
    url: "https://brightraven.world",
  },
  social: {
    github: "https://github.com/devBrightRaven",
  },
  // UI strings per language
  i18n: {
    en: {
      siteTitle: "曉 Akatsuki",
      tagline: "Notes on AI, accessibility, games, and how people retain agency within systems.",
      seriesKicker: "ESSAYS ON AGENCY",
      moreStories: "MORE STORIES",
      stories: "stories",
      page: "Page",
      of: "of",
      pageSuffix: "",
      previousPage: "Previous page",
      nextPage: "Next page",
      pagination: "Article pages",
      languageNavigation: "Languages",
      presentationLabel: "Visual presentation",
      presentationArticles: "Articles",
      presentationCalligraphy: "曉",
      startHere: "Start here",
      previousStory: "Previous story",
      nextStory: "Next story",
      storyNavigation: "Continue reading",
      allStories: "All articles",
      readMore: "Read more",
      home: "Home",
      allPosts: "All articles",
      readingTime: "min read",
      skipToContent: "Skip to main content",
      footerDescription: "studies and builds tools that help people retain understanding, choice, and agency.",
      noNewsletter: "No newsletter. Follow by RSS, or come back whenever you like.",
      backToTop: "Back to top",
    },
    ja: {
      siteTitle: "曉 Akatsuki",
      tagline: "AI、アクセシビリティ、ゲーム、そして人がシステムの中でいかに選択する力を保つかについての記録。",
      seriesKicker: "主体性をめぐるエッセイ",
      moreStories: "ほかの記事",
      stories: "本の記事",
      page: "ページ",
      of: "/",
      pageSuffix: "",
      previousPage: "前のページ",
      nextPage: "次のページ",
      pagination: "記事ページ",
      languageNavigation: "言語",
      presentationLabel: "表示",
      presentationArticles: "記事",
      presentationCalligraphy: "曉",
      startHere: "ここから読む",
      previousStory: "前の記事",
      nextStory: "次の記事",
      storyNavigation: "続きを読む",
      allStories: "すべての記事",
      readMore: "続きを読む",
      home: "ホーム",
      allPosts: "すべての記事",
      readingTime: "分で読めます",
      skipToContent: "本文へ移動",
      footerDescription: "人が理解し、選び、行動する力を保つために研究し、ツールをつくっています。",
      noNewsletter: "ニュースレターは配信していません。RSSで購読するか、また読みたくなったときにお越しください。",
      backToTop: "ページ上部へ",
    },
    "zh-TW": {
      siteTitle: "曉 Akatsuki",
      tagline: "關於 AI、無障礙、遊戲，以及人在系統中如何保有選擇的筆記。",
      seriesKicker: "關於能動性的文章",
      moreStories: "更多故事",
      stories: "篇故事",
      page: "第",
      of: "頁，共",
      pageSuffix: " 頁",
      previousPage: "上一頁",
      nextPage: "下一頁",
      pagination: "文章分頁",
      languageNavigation: "語言",
      presentationLabel: "視覺呈現",
      presentationArticles: "文章",
      presentationCalligraphy: "曉",
      startHere: "從這裡開始",
      previousStory: "上一篇",
      nextStory: "下一篇",
      storyNavigation: "繼續閱讀",
      allStories: "所有文章",
      readMore: "繼續閱讀",
      home: "首頁",
      allPosts: "所有文章",
      readingTime: "分鐘",
      skipToContent: "跳至主要內容",
      footerDescription: "研究並製作幫助人保有理解、選擇與行動能力的工具。",
      noNewsletter: "不寄電子報。你可以透過 RSS 追蹤，或想起來時再回來看看。",
      backToTop: "回到頁首",
    },
  },
}
