export default {
  title: "Bright Raven",
  url: "https://blog.brightraven.world",
  feedUrl: {
    en: "/feed.xml",
    ja: "/ja/feed.xml",
    "zh-TW": "/zh/feed.xml",
  },
  routes: {
    en: { latest: "/", series: "/series/", topics: "/topics/" },
    ja: { latest: "/ja/", series: "/ja/series/", topics: "/ja/topics/" },
    "zh-TW": { latest: "/zh/", series: "/zh/series/", topics: "/zh/topics/" },
  },
  series: {
    playersNotInfinite: {
      id: "players-not-infinite",
      title: {
        en: "Players Are Not Infinite",
        ja: "プレイヤーは無限ではない",
        "zh-TW": "玩家不是無限的",
      },
      description: {
        en: "Games can keep multiplying. A player's time, attention, and body cannot.",
        ja: "ゲームは増え続けても、プレイヤーの時間、注意力、身体は増えない。",
        "zh-TW": "遊戲可以一直增加，但玩家能投入的時間、注意力與身體不會跟著增加。",
      },
    },
    maidaRedesign: {
      id: "maida-reasons-to-open",
      title: {
        "zh-TW": "值得打開的理由",
      },
      description: {
        "zh-TW": "為什麼值得打開 Maida，也為什麼此刻值得打開某一款遊戲。",
      },
    },
  },
  topicCatalog: [
    {
      id: "games",
      labels: { en: "Games", ja: "ゲーム", "zh-TW": "遊戲" },
      description: {
        en: "How games are made, sold, and lived with.",
        ja: "ゲームがつくられ、売られ、生活の中で遊ばれるまで。",
        "zh-TW": "遊戲如何被製作、販售，也如何進入生活。",
      },
    },
    {
      id: "ai",
      labels: { en: "AI", ja: "AI", "zh-TW": "AI" },
      description: {
        en: "How AI changes the systems people use and make.",
        ja: "AI が人の使う仕組みと、つくる仕組みをどう変えるか。",
        "zh-TW": "AI 如何改變人們使用與建構的系統。",
      },
    },
    {
      id: "accessibility",
      labels: { en: "Accessibility", ja: "アクセシビリティ", "zh-TW": "無障礙" },
      description: {
        en: "Whether a system leaves room for more people to take part.",
        ja: "より多くの人が参加できる余地を、仕組みが残しているか。",
        "zh-TW": "系統是否為更多人留下參與的空間。",
      },
    },
    {
      id: "agency",
      labels: { en: "Agency", ja: "主体性", "zh-TW": "能動性" },
      description: {
        en: "How people retain judgment and room to act within systems.",
        ja: "仕組みの中で、人が判断と行動の余地を保つにはどうすればよいか。",
        "zh-TW": "人在系統中如何保有判斷與行動的空間。",
      },
    },
    {
      id: "choice",
      labels: { en: "Choice", ja: "選択", "zh-TW": "選擇" },
      description: {
        en: "What makes a choice feel possible, informed, and one's own.",
        ja: "選択が可能で、理解に基づき、自分のものだと感じられる条件。",
        "zh-TW": "讓選擇成為可能、知情且屬於自己的條件。",
      },
    },
    {
      id: "systems-responsibility",
      labels: { en: "Systems and responsibility", ja: "システムと責任", "zh-TW": "系統與責任" },
      description: {
        en: "Where responsibility sits when systems shape everyday decisions.",
        ja: "仕組みが日常の判断を形づくるとき、責任はどこにあるのか。",
        "zh-TW": "當系統塑造日常判斷時，責任落在何處。",
      },
    },
  ],
  author: {
    name: "Bertram (Bright Raven)",
    email: "bertram@brightraven.world",
  },
  studio: {
    name: "Bright Raven",
    url: "https://brightraven.world",
  },
  social: {
    github: "https://github.com/devBrightRaven",
  },
  // UI strings per language
  i18n: {
    en: {
      siteTitle: "曉 Akatsuki",
      tagline: "Notes on AI, accessibility, games, and how people retain agency within systems.",
      seriesKicker: "ESSAYS ON AGENCY",
      moreStories: "MORE STORIES",
      stories: "stories",
      page: "Page",
      of: "of",
      pageSuffix: "",
      previousPage: "Previous page",
      nextPage: "Next page",
      pagination: "Article pages",
      contentNavigation: "Content navigation",
      languageNavigation: "Languages",
      presentationLabel: "Visual presentation",
      presentationArticles: "Articles",
      presentationCalligraphy: "曉",
      latest: "Latest",
      series: "Series",
      topicMap: "Topic map",
      topicMapLabel: "Topic map relationships",
      tags: "Tags",
      theme: "Theme",
      themeAuto: "Auto",
      themeLight: "Light",
      themeDark: "Dark",
      privacyChoices: "Privacy choices",
      startSeries: "Start the series",
      recommendedStart: "Recommended start",
      readingOrder: "Reading order",
      startHere: "Start here",
      previousStory: "Previous story",
      nextStory: "Next story",
      storyNavigation: "Continue reading",
      topics: "Topics",
      allStories: "All articles",
      readMore: "Read more",
      home: "Home",
      allPosts: "All articles",
      readingTime: "min read",
      skipToContent: "Skip to main content",
      footerDescription: "studies and builds tools that help people retain understanding, choice, and agency.",
      noNewsletter: "No newsletter. Follow by RSS, or come back whenever you like.",
      backToTop: "Back to top",
    },
    ja: {
      siteTitle: "曉 Akatsuki",
      tagline: "AI、アクセシビリティ、ゲーム、そして人がシステムの中でいかに選択する力を保つかについての記録。",
      seriesKicker: "主体性をめぐるエッセイ",
      moreStories: "ほかの記事",
      stories: "本の記事",
      page: "ページ",
      of: "/",
      pageSuffix: "",
      previousPage: "前のページ",
      nextPage: "次のページ",
      pagination: "記事ページ",
      contentNavigation: "コンテンツナビゲーション",
      languageNavigation: "言語",
      presentationLabel: "表示",
      presentationArticles: "記事",
      presentationCalligraphy: "曉",
      latest: "最新",
      series: "シリーズ",
      topicMap: "トピックマップ",
      topicMapLabel: "トピックマップの関係",
      tags: "タグ",
      theme: "テーマ",
      themeAuto: "自動",
      themeLight: "ライト",
      themeDark: "ダーク",
      privacyChoices: "プライバシー設定",
      startSeries: "シリーズを読む",
      recommendedStart: "おすすめの開始位置",
      readingOrder: "読む順番",
      startHere: "ここから読む",
      previousStory: "前の記事",
      nextStory: "次の記事",
      storyNavigation: "続きを読む",
      topics: "トピック",
      allStories: "すべての記事",
      readMore: "続きを読む",
      home: "ホーム",
      allPosts: "すべての記事",
      readingTime: "分で読めます",
      skipToContent: "本文へ移動",
      footerDescription: "人が理解し、選び、行動する力を保つために研究し、ツールをつくっています。",
      noNewsletter: "ニュースレターは配信していません。RSSで購読するか、また読みたくなったときにお越しください。",
      backToTop: "ページ上部へ",
    },
    "zh-TW": {
      siteTitle: "曉 Akatsuki",
      tagline: "關於 AI、無障礙、遊戲，以及人在系統中如何保有選擇的筆記。",
      seriesKicker: "關於能動性的文章",
      moreStories: "更多故事",
      stories: "篇故事",
      page: "第",
      of: "頁，共",
      pageSuffix: " 頁",
      previousPage: "上一頁",
      nextPage: "下一頁",
      pagination: "文章分頁",
      contentNavigation: "內容導覽",
      languageNavigation: "語言",
      presentationLabel: "視覺呈現",
      presentationArticles: "文章",
      presentationCalligraphy: "曉",
      latest: "最新",
      series: "系列",
      topicMap: "主題地圖",
      topicMapLabel: "主題地圖關係",
      tags: "標籤",
      theme: "主題",
      themeAuto: "自動",
      themeLight: "淺色",
      themeDark: "深色",
      privacyChoices: "隱私選項",
      startSeries: "開始閱讀系列",
      recommendedStart: "建議起點",
      readingOrder: "閱讀順序",
      startHere: "從這裡開始",
      previousStory: "上一篇",
      nextStory: "下一篇",
      storyNavigation: "繼續閱讀",
      topics: "主題",
      allStories: "所有文章",
      readMore: "繼續閱讀",
      home: "首頁",
      allPosts: "所有文章",
      readingTime: "分鐘",
      skipToContent: "跳至主要內容",
      footerDescription: "研究並製作幫助人保有理解、選擇與行動能力的工具。",
      noNewsletter: "不寄電子報。你可以透過 RSS 追蹤，或想起來時再回來看看。",
      backToTop: "回到頁首",
    },
  },
}
