export default {
  title: "Bright Raven",
  url: "https://blog.brightraven.world",
  feedUrl: {
    en: "/feed.xml",
    "zh-TW": "/zh/feed.xml",
  },
  author: {
    name: "Bertram (Bright Raven)",
    email: "bertram@brightraven.world",
  },
  product: {
    name: "Maida",
    url: "https://brightraven.world",
    tagline: "Bring back your agency",
  },
  social: {
    github: "https://github.com/devBrightRaven",
  },
  // UI strings per language
  i18n: {
    en: {
      siteTitle: "曉 Akatsuki",
      tagline: "Notes on decision paralysis, agency, and gaming.",
      seriesKicker: "NINE PLACES TO BEGIN",
      moreStories: "MORE STORIES",
      stories: "stories",
      page: "Page",
      of: "of",
      pageSuffix: "",
      previousPage: "Previous page",
      nextPage: "Next page",
      pagination: "Article pages",
      startHere: "Start here",
      previousStory: "Previous story",
      nextStory: "Next story",
      storyNavigation: "Continue reading",
      allStories: "All articles",
      readMore: "Read more",
      switchLang: "中文",
      switchLangCode: "zh-TW",
      home: "Home",
      allPosts: "All articles",
      readingTime: "min read",
      skipToContent: "Skip to main content",
      productCTA: "Maida is a free, open-source tool for choosing what to play tonight.",
      noNewsletter: "No newsletter. RSS or come back when you remember.",
    },
    "zh-TW": {
      siteTitle: "曉 Akatsuki",
      tagline: "關於決策疲勞、能動性與遊戲的筆記。",
      seriesKicker: "九個開始閱讀的入口",
      moreStories: "更多故事",
      stories: "篇故事",
      page: "第",
      of: "頁，共",
      pageSuffix: " 頁",
      previousPage: "上一頁",
      nextPage: "下一頁",
      pagination: "文章分頁",
      startHere: "從這裡開始",
      previousStory: "上一篇",
      nextStory: "下一篇",
      storyNavigation: "繼續閱讀",
      allStories: "所有文章",
      readMore: "繼續閱讀",
      switchLang: "English",
      switchLangCode: "en",
      home: "首頁",
      allPosts: "所有文章",
      readingTime: "分鐘",
      skipToContent: "跳至主要內容",
      productCTA: "Maida 是一個免費、開源的工具，幫你決定今晚玩什麼。",
      noNewsletter: "沒有電子報。用 RSS 訂閱，或想到再回來。",
    },
  },
}
